apiVersion: apps/v1
kind: Deployment

metadata:
  name: order-deployment
  namespace: sm

spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
        # AWS의 ECR를 사용 
          image: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com/sangmin-order:latest
          ports: 
            - containerPort: 8080
          resources:
            limits: # 최대 할당량
              cpu: "0.5"
              memory: "500Mi"
            requests: # 최소 할당량
              cpu: "0.25"
              memory: "250Mi"
          env:
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                key: REDIS_HOST
                name: sm-app-secrets

          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                key: DB_HOST
                name: sm-app-secrets

          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                key: DB_USERNAME
                name: sm-app-secrets

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: DB_PASSWORD
                name: sm-app-secrets

          - name: AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: AWS_ACCESS_KEY
                name: sm-app-secrets

          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: AWS_SECRET_KEY
                name: sm-app-secrets
          
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: JWT_SECRET_KEY
                name: sm-app-secrets

          - name: JWT_SECRET_KEY_RT
            valueFrom:
              secretKeyRef:
                key: JWT_SECRET_KEY_RT
                name: sm-app-secrets
