apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  namespace: sm
  labels:
    app: sm-nginx

spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80


---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  namespace: sm
  labels:
    app: sm-nginx

spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: sm
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30510
  selector:
    app: sm-nginx
